CIFAR_10_CONV_NAME = "cifar10_conv_model"
CIFAR_100_CONV_NAME = "cifar100_conv_model"
INCEPTION_V3_NAME = "imagenet_v3"
RESNET_NAME = "resnet152v2"
MNIST_CONV_NAME = "mnist_conv_model"
MNIST_DENSE_NAME = "mnist_dense_model"
LE_NET_NAME = "le_net_model"