PARAMETERS_KEY = "parameters"
DATASET_KEY = "dataset"
BATCHES_KEY = "batch"
NMB_ELEMENTS_KEY = "nmb_elements"
MODEL_NAME_KEY = "model_name"
L2_MEDIAN_KEY = "L2_median"
L2_AVERAGE_KEY = "L2_average"
AVG_TIME_SAMPLE_KEY = "average_time_per_sample"
ACCURACY_KEY = "accuracy_result"
ATTACK_NAME_KEY = "attack_name"
TOTAL_TIME_KEY = "total_time"

